[package]
name = "uav-ground-control-station"
version = "0.2.19"
description = "Native desktop shell for UAV Ground Control Station"
authors = ["F. Eber"]
license = "GPL-3.0-only"
edition = "2021"

[lib]
name = "uav_ground_control_station_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
geo-types = "0.7"
geotiff = "0.1"
tiff = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
